services:
  nginx:
    build: ./docker/nginx
    container_name: nginx.${APP_NAME}
    ports:
      - '${NGINX_HTTP_PORT}:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
    container_name: php-fpm.${APP_NAME}
    volumes:
      - .:/var/www/html